# Generated by Django 4.1.4 on 2022-12-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Car',
        ),
    ]
