# Generated by Django 4.1.4 on 2023-02-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
