# Generated by Django 4.1.4 on 2023-02-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_cardetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
